### ISSUE TITLE
Please implement/support HmIP-WKP (Keypad)

### ISSUE THREAD

**Issue by LucTs** [hahn-th/homematicip-rest-api#457]
Hi,

would be great if you can add support for the HmIP keypad. Please find the config dump attached.

**Comment by hahn-th** [comment]
Hi,
there is nothing yet implemented for that device. I think you have to reverse engineer the commands, which are send by the keypad. 
Another problem: maybe its not possible to track the button presses because this lib is only able to see events, which are send by the app. If devices communicate between each other, we dont see anything.

You want to use the keypad in home-assistant?

**Comment by LucTs** [comment]
Hi,

okay, understood. Yes, first I thought the integration to HA might be helpful but the more I´m thinking about I´m wondering what would be the use/case value... :)

**Comment by LucTs** [comment]
Closing since not required as of now.

**Comment by hahn-th** [comment]
We could try implement it, but i need your help. 
But at the end you gonna tigger something you could trigger more easy with your smartphone or somehing. Or maybe even with a nfc tag.

**Comment by coreGreenberet** [comment]
Sadly,  button presses are not delivered over the api. (Even though that there are events in the code for it)
